---
title: "Exploring eBird data from 2015 to 2023"
author: "Bianca Neves"
date: "02/09/24"
output:
  html_document:
    toc: yes
    toc_float: yes
    theme: paper
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(dplyr)
library(tidyr) # for organized code
library(sf, sp) # for reading shp and ploting

```

# Data $1km^2$, $4km^2 and $9km^2$,
The data is from eBird for the period from 2015 to 2023, covering the urban area of the city of São Paulo. Only cells with 30 minutes or more of observation and 10 or more bird species were selected.

```{r data, include=FALSE}
# sum of species
#shp <- st_read("Z:/Bianca/eBird/Data/1km_urb_f1km/richness_effort_v13_total_1km_urb_f1km_30min_10spp.shp")
shp_1 <- st_read("C:/Users/Bianca/Documents/USP/Projeto/eBird/Data/1km/richness_effort_v13_total_1km_urb_f1km_30min_10spp.shp")
data_1km <- shp_1
data_1km$scale <- "1 km²" 

#shp <- st_read("Z:/Bianca/eBird/Data/2km_urb_f2.5km/richness_effort_v13_total_2km_urb_f2.5km_30min_10spp.shp")
shp_4 <- st_read("C:/Users/Bianca/Documents/USP/Projeto/eBird/Data/2km/richness_effort_v13_total_2km_urb_f2.5km_30min_10spp.shp")
data_4km <- shp_4
data_4km$scale <- "4 km²"

#shp_9 <- st_read("Z:/Bianca/eBird/Data/3km_urb_fkm/richness_effort_v13_total_3km_urb_f5km_30min_10spp.shp")
shp_9 <- st_read("C:/Users/Bianca/Documents/USP/Projeto/eBird/Data/3km/richness_effort_v13_total_3km_urb_f5km_30min_10spp.shp")
data_9km <- shp_9
data_9km$scale <- "9 km²"

# Combine datasets into one data frame
combined_data <- bind_rows(data_1km, data_4km, data_9km)
```

# Richness
```{r, echo=FALSE}
ggplot(combined_data, aes(x = richness, fill = scale)) +
  geom_density(alpha = 0.5) +
  labs(x = "Richness", y = "Density") +
  ggtitle("Species richness by scale") +
  theme_classic() +
  theme(
    legend.position = "bottom",
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 14),
    plot.title = element_text(size = 16, face = "bold")
  )
```
```{r, echo=FALSE}
ggplot(combined_data, aes(x = richness, fill = scale)) +
  geom_histogram(aes(y = after_stat(count / sum(count))), position = "dodge", binwidth = 5, alpha = 0.7, color = "black") +
  labs(x = "Richness", y = "Proportion") +
  ggtitle("Species richness by scale") +
  theme_classic() +
  theme(
    legend.position = "bottom",
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 14),
    plot.title = element_text(size = 16, face = "bold")
  )
```
```{r, echo=FALSE}  
# Boxplot for species richness
ggplot(combined_data, aes(x = scale, y = richness, fill = scale)) +
  geom_boxplot() +
  geom_jitter(color = "black", size = 2, alpha = 0.1) +
  labs(x = "Scale", y = "Richness") +
  ggtitle("Species richness by scale") +
  theme_classic() +
  theme(
    legend.position = "none",
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 14),
    plot.title = element_text(size = 16, face = "bold")
  )
```
# Time effort
Sum of the total time in minutes of independent sampling (filtered by person and by group).
```{r, echo=FALSE}
ggplot(combined_data, aes(x = effort * 60, fill = scale)) +
  geom_density(alpha = 0.5) +
  labs(x = "Effort (hours)", y = "Density") +
  ggtitle("Time effort by rcale") +
  theme_classic() +
  theme(
    legend.position = "bottom",
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 14),
    plot.title = element_text(size = 16, face = "bold")
  )
```
```{r, echo=FALSE}
ggplot(combined_data, aes(x = effort * 60, fill = scale)) +
  geom_histogram(aes(y = after_stat(count / sum(count))), position = "dodge", binwidth = 60, alpha = 0.7, color = "black") +
  labs(x = "Effort (hours)", y = "Proportion") +
  ggtitle("Time effort by scale") +
  theme_classic() +
  theme(
    legend.position = "bottom",
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 14),
    plot.title = element_text(size = 16, face = "bold")
  )
```
```{r, echo=FALSE}  
# Boxplot for effort
ggplot(combined_data, aes(x = scale, y = effort * 60, fill = scale)) +
  geom_boxplot() +
  geom_jitter(color = "black", size = 2, alpha = 0.1) +
  labs(x = "Scale", y = "Effort (hours)") +
  ggtitle("Time effort by scale") +
  theme_classic() +
  theme(
    legend.position = "none",
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 14),
    plot.title = element_text(size = 16, face = "bold")
  )
```


## Time effort for different scales

```{r, echo=FALSE}
# Histogram with binwidth = 100 and y as proportion, colored by scale
ggplot(combined_data, aes(x = effort / 60, fill = scale)) +
  geom_histogram(aes(y = after_stat(count / sum(count))), binwidth = 100, color = "black", alpha = 0.7) + 
  labs(x = "Effort (hour)", y = "Proportion") +
  theme_classic() + 
  theme(
    legend.position = "top",
    axis.title = element_text(size = 14),  
    axis.text = element_text(size = 14),
    plot.title = element_text(size = 16, face = "bold")
  ) +
  ggtitle("Time effort by scale")

# Histogram with binwidth = 10 and xlim adjusted to 0-100 and y as proportion, colored by scale
ggplot(combined_data, aes(x = effort / 60, fill = scale)) +
  geom_histogram(aes(y = after_stat(count / sum(count))), binwidth = 10, color = "black", alpha = 0.7) + 
  labs(x = "Effort (hour)", y = "Proportion") +
  coord_cartesian(xlim = c(0, 100)) +
  theme_classic() + 
  theme(
    legend.position = "top",
    axis.title = element_text(size = 14),  
    axis.text = element_text(size = 14),
    plot.title = element_text(size = 16, face = "bold")
  ) +
  ggtitle("Time effort by scale")

# Histogram with binwidth = 1 and xlim adjusted to 0-50 and y as proportion, colored by scale
ggplot(combined_data, aes(x = effort / 60, fill = scale)) +
  geom_histogram(aes(y = after_stat(count / sum(count))), binwidth = 1, color = "black", alpha = 0.7) + 
  labs(x = "Effort (hour)", y = "Proportion") +
  coord_cartesian(xlim = c(0, 50)) +
  theme_classic() + 
  theme(
    legend.position = "top",
    axis.title = element_text(size = 14),  
    axis.text = element_text(size = 14),
    plot.title = element_text(size = 16, face = "bold")
  ) +
  ggtitle("Time effort by scale")

```
